//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AlexAndNikkiDBModel", "FK_BlogPosts_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AlexAndNikki.Models.User), "BlogPosts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AlexAndNikki.Models.BlogPost), true)]
[assembly: EdmRelationshipAttribute("AlexAndNikkiDBModel", "FK_Profiles_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AlexAndNikki.Models.User), "Profiles", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AlexAndNikki.Models.Profile), true)]
[assembly: EdmRelationshipAttribute("AlexAndNikkiDBModel", "FK_BlogPostComments_BlogPosts", "BlogPost", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AlexAndNikki.Models.BlogPost), "BlogPostComment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AlexAndNikki.Models.BlogPostComment), true)]
[assembly: EdmRelationshipAttribute("AlexAndNikkiDBModel", "FK_WeddingInvitees_WeddingInvites", "Invite", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AlexAndNikki.Models.Invite), "Guest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AlexAndNikki.Models.Guest), true)]

#endregion

namespace AlexAndNikki.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AlexAndNikkiDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AlexAndNikkiDBEntities object using the connection string found in the 'AlexAndNikkiDBEntities' section of the application configuration file.
        /// </summary>
        public AlexAndNikkiDBEntities() : base("name=AlexAndNikkiDBEntities", "AlexAndNikkiDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AlexAndNikkiDBEntities object.
        /// </summary>
        public AlexAndNikkiDBEntities(string connectionString) : base(connectionString, "AlexAndNikkiDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AlexAndNikkiDBEntities object.
        /// </summary>
        public AlexAndNikkiDBEntities(EntityConnection connection) : base(connection, "AlexAndNikkiDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BlogPostComment> BlogPostComments
        {
            get
            {
                if ((_BlogPostComments == null))
                {
                    _BlogPostComments = base.CreateObjectSet<BlogPostComment>("BlogPostComments");
                }
                return _BlogPostComments;
            }
        }
        private ObjectSet<BlogPostComment> _BlogPostComments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BlogPost> BlogPosts
        {
            get
            {
                if ((_BlogPosts == null))
                {
                    _BlogPosts = base.CreateObjectSet<BlogPost>("BlogPosts");
                }
                return _BlogPosts;
            }
        }
        private ObjectSet<BlogPost> _BlogPosts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Photo> Photos
        {
            get
            {
                if ((_Photos == null))
                {
                    _Photos = base.CreateObjectSet<Photo>("Photos");
                }
                return _Photos;
            }
        }
        private ObjectSet<Photo> _Photos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Profile> Profiles
        {
            get
            {
                if ((_Profiles == null))
                {
                    _Profiles = base.CreateObjectSet<Profile>("Profiles");
                }
                return _Profiles;
            }
        }
        private ObjectSet<Profile> _Profiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StaticPage> StaticPages
        {
            get
            {
                if ((_StaticPages == null))
                {
                    _StaticPages = base.CreateObjectSet<StaticPage>("StaticPages");
                }
                return _StaticPages;
            }
        }
        private ObjectSet<StaticPage> _StaticPages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Invite> Invites
        {
            get
            {
                if ((_Invites == null))
                {
                    _Invites = base.CreateObjectSet<Invite>("Invites");
                }
                return _Invites;
            }
        }
        private ObjectSet<Invite> _Invites;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Guest> Guests
        {
            get
            {
                if ((_Guests == null))
                {
                    _Guests = base.CreateObjectSet<Guest>("Guests");
                }
                return _Guests;
            }
        }
        private ObjectSet<Guest> _Guests;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BlogPostComments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlogPostComments(BlogPostComment blogPostComment)
        {
            base.AddObject("BlogPostComments", blogPostComment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BlogPosts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlogPosts(BlogPost blogPost)
        {
            base.AddObject("BlogPosts", blogPost);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Photos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhotos(Photo photo)
        {
            base.AddObject("Photos", photo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Profiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProfiles(Profile profile)
        {
            base.AddObject("Profiles", profile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StaticPages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStaticPages(StaticPage staticPage)
        {
            base.AddObject("StaticPages", staticPage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Invites EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInvites(Invite invite)
        {
            base.AddObject("Invites", invite);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Guests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGuests(Guest guest)
        {
            base.AddObject("Guests", guest);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlexAndNikkiDBModel", Name="BlogPost")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BlogPost : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BlogPost object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="author">Initial value of the Author property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="body">Initial value of the Body property.</param>
        /// <param name="friendlyUrl">Initial value of the FriendlyUrl property.</param>
        public static BlogPost CreateBlogPost(global::System.Int32 id, global::System.String author, global::System.DateTime date, global::System.String title, global::System.String body, global::System.String friendlyUrl)
        {
            BlogPost blogPost = new BlogPost();
            blogPost.Id = id;
            blogPost.Author = author;
            blogPost.Date = date;
            blogPost.Title = title;
            blogPost.Body = body;
            blogPost.FriendlyUrl = friendlyUrl;
            return blogPost;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author;
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Summary
        {
            get
            {
                return _Summary;
            }
            set
            {
                OnSummaryChanging(value);
                ReportPropertyChanging("Summary");
                _Summary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Summary");
                OnSummaryChanged();
            }
        }
        private global::System.String _Summary;
        partial void OnSummaryChanging(global::System.String value);
        partial void OnSummaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FriendlyUrl
        {
            get
            {
                return _FriendlyUrl;
            }
            set
            {
                OnFriendlyUrlChanging(value);
                ReportPropertyChanging("FriendlyUrl");
                _FriendlyUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FriendlyUrl");
                OnFriendlyUrlChanged();
            }
        }
        private global::System.String _FriendlyUrl;
        partial void OnFriendlyUrlChanging(global::System.String value);
        partial void OnFriendlyUrlChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlexAndNikkiDBModel", "FK_BlogPosts_Users", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AlexAndNikkiDBModel.FK_BlogPosts_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AlexAndNikkiDBModel.FK_BlogPosts_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AlexAndNikkiDBModel.FK_BlogPosts_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("AlexAndNikkiDBModel.FK_BlogPosts_Users", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlexAndNikkiDBModel", "FK_BlogPostComments_BlogPosts", "BlogPostComment")]
        public EntityCollection<BlogPostComment> BlogPostComments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BlogPostComment>("AlexAndNikkiDBModel.FK_BlogPostComments_BlogPosts", "BlogPostComment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BlogPostComment>("AlexAndNikkiDBModel.FK_BlogPostComments_BlogPosts", "BlogPostComment", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlexAndNikkiDBModel", Name="BlogPostComment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BlogPostComment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BlogPostComment object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="comment">Initial value of the Comment property.</param>
        /// <param name="blogPostId">Initial value of the BlogPostId property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static BlogPostComment CreateBlogPostComment(global::System.Int32 id, global::System.String comment, global::System.Int32 blogPostId, global::System.DateTime date)
        {
            BlogPostComment blogPostComment = new BlogPostComment();
            blogPostComment.Id = id;
            blogPostComment.Comment = comment;
            blogPostComment.BlogPostId = blogPostId;
            blogPostComment.Date = date;
            return blogPostComment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Website
        {
            get
            {
                return _Website;
            }
            set
            {
                OnWebsiteChanging(value);
                ReportPropertyChanging("Website");
                _Website = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Website");
                OnWebsiteChanged();
            }
        }
        private global::System.String _Website;
        partial void OnWebsiteChanging(global::System.String value);
        partial void OnWebsiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BlogPostId
        {
            get
            {
                return _BlogPostId;
            }
            set
            {
                OnBlogPostIdChanging(value);
                ReportPropertyChanging("BlogPostId");
                _BlogPostId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BlogPostId");
                OnBlogPostIdChanged();
            }
        }
        private global::System.Int32 _BlogPostId;
        partial void OnBlogPostIdChanging(global::System.Int32 value);
        partial void OnBlogPostIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlexAndNikkiDBModel", "FK_BlogPostComments_BlogPosts", "BlogPost")]
        public BlogPost BlogPost
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BlogPost>("AlexAndNikkiDBModel.FK_BlogPostComments_BlogPosts", "BlogPost").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BlogPost>("AlexAndNikkiDBModel.FK_BlogPostComments_BlogPosts", "BlogPost").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BlogPost> BlogPostReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BlogPost>("AlexAndNikkiDBModel.FK_BlogPostComments_BlogPosts", "BlogPost");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BlogPost>("AlexAndNikkiDBModel.FK_BlogPostComments_BlogPosts", "BlogPost", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlexAndNikkiDBModel", Name="Guest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Guest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Guest object.
        /// </summary>
        /// <param name="guestID">Initial value of the GuestID property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="inviteID">Initial value of the InviteID property.</param>
        /// <param name="confirmReception">Initial value of the ConfirmReception property.</param>
        /// <param name="confirmCeremony">Initial value of the ConfirmCeremony property.</param>
        /// <param name="invitedToCeremony">Initial value of the InvitedToCeremony property.</param>
        /// <param name="primaryGuest">Initial value of the PrimaryGuest property.</param>
        public static Guest CreateGuest(global::System.Int16 guestID, global::System.String firstName, global::System.String lastName, global::System.String inviteID, global::System.String confirmReception, global::System.String confirmCeremony, global::System.Boolean invitedToCeremony, global::System.Boolean primaryGuest)
        {
            Guest guest = new Guest();
            guest.GuestID = guestID;
            guest.FirstName = firstName;
            guest.LastName = lastName;
            guest.InviteID = inviteID;
            guest.ConfirmReception = confirmReception;
            guest.ConfirmCeremony = confirmCeremony;
            guest.InvitedToCeremony = invitedToCeremony;
            guest.PrimaryGuest = primaryGuest;
            return guest;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 GuestID
        {
            get
            {
                return _GuestID;
            }
            set
            {
                if (_GuestID != value)
                {
                    OnGuestIDChanging(value);
                    ReportPropertyChanging("GuestID");
                    _GuestID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GuestID");
                    OnGuestIDChanged();
                }
            }
        }
        private global::System.Int16 _GuestID;
        partial void OnGuestIDChanging(global::System.Int16 value);
        partial void OnGuestIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZipCode
        {
            get
            {
                return _ZipCode;
            }
            set
            {
                OnZipCodeChanging(value);
                ReportPropertyChanging("ZipCode");
                _ZipCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZipCode");
                OnZipCodeChanged();
            }
        }
        private global::System.String _ZipCode;
        partial void OnZipCodeChanging(global::System.String value);
        partial void OnZipCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Relationship
        {
            get
            {
                return _Relationship;
            }
            set
            {
                OnRelationshipChanging(value);
                ReportPropertyChanging("Relationship");
                _Relationship = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Relationship");
                OnRelationshipChanged();
            }
        }
        private global::System.String _Relationship;
        partial void OnRelationshipChanging(global::System.String value);
        partial void OnRelationshipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InviteID
        {
            get
            {
                return _InviteID;
            }
            set
            {
                OnInviteIDChanging(value);
                ReportPropertyChanging("InviteID");
                _InviteID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("InviteID");
                OnInviteIDChanged();
            }
        }
        private global::System.String _InviteID;
        partial void OnInviteIDChanging(global::System.String value);
        partial void OnInviteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ConfirmReception
        {
            get
            {
                return _ConfirmReception;
            }
            set
            {
                OnConfirmReceptionChanging(value);
                ReportPropertyChanging("ConfirmReception");
                _ConfirmReception = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ConfirmReception");
                OnConfirmReceptionChanged();
            }
        }
        private global::System.String _ConfirmReception;
        partial void OnConfirmReceptionChanging(global::System.String value);
        partial void OnConfirmReceptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ConfirmCeremony
        {
            get
            {
                return _ConfirmCeremony;
            }
            set
            {
                OnConfirmCeremonyChanging(value);
                ReportPropertyChanging("ConfirmCeremony");
                _ConfirmCeremony = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ConfirmCeremony");
                OnConfirmCeremonyChanged();
            }
        }
        private global::System.String _ConfirmCeremony;
        partial void OnConfirmCeremonyChanging(global::System.String value);
        partial void OnConfirmCeremonyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean InvitedToCeremony
        {
            get
            {
                return _InvitedToCeremony;
            }
            set
            {
                OnInvitedToCeremonyChanging(value);
                ReportPropertyChanging("InvitedToCeremony");
                _InvitedToCeremony = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvitedToCeremony");
                OnInvitedToCeremonyChanged();
            }
        }
        private global::System.Boolean _InvitedToCeremony;
        partial void OnInvitedToCeremonyChanging(global::System.Boolean value);
        partial void OnInvitedToCeremonyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PrimaryGuest
        {
            get
            {
                return _PrimaryGuest;
            }
            set
            {
                OnPrimaryGuestChanging(value);
                ReportPropertyChanging("PrimaryGuest");
                _PrimaryGuest = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrimaryGuest");
                OnPrimaryGuestChanged();
            }
        }
        private global::System.Boolean _PrimaryGuest;
        partial void OnPrimaryGuestChanging(global::System.Boolean value);
        partial void OnPrimaryGuestChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlexAndNikkiDBModel", "FK_WeddingInvitees_WeddingInvites", "Invite")]
        public Invite Invite
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Invite>("AlexAndNikkiDBModel.FK_WeddingInvitees_WeddingInvites", "Invite").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Invite>("AlexAndNikkiDBModel.FK_WeddingInvitees_WeddingInvites", "Invite").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Invite> InviteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Invite>("AlexAndNikkiDBModel.FK_WeddingInvitees_WeddingInvites", "Invite");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Invite>("AlexAndNikkiDBModel.FK_WeddingInvitees_WeddingInvites", "Invite", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlexAndNikkiDBModel", Name="Invite")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Invite : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Invite object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="relatedFamily">Initial value of the RelatedFamily property.</param>
        public static Invite CreateInvite(global::System.String id, global::System.String relatedFamily)
        {
            Invite invite = new Invite();
            invite.Id = id;
            invite.RelatedFamily = relatedFamily;
            return invite;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RelatedFamily
        {
            get
            {
                return _RelatedFamily;
            }
            set
            {
                OnRelatedFamilyChanging(value);
                ReportPropertyChanging("RelatedFamily");
                _RelatedFamily = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RelatedFamily");
                OnRelatedFamilyChanged();
            }
        }
        private global::System.String _RelatedFamily;
        partial void OnRelatedFamilyChanging(global::System.String value);
        partial void OnRelatedFamilyChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlexAndNikkiDBModel", "FK_WeddingInvitees_WeddingInvites", "Guest")]
        public EntityCollection<Guest> Guests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Guest>("AlexAndNikkiDBModel.FK_WeddingInvitees_WeddingInvites", "Guest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Guest>("AlexAndNikkiDBModel.FK_WeddingInvitees_WeddingInvites", "Guest", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlexAndNikkiDBModel", Name="Photo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Photo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Photo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="imageURL">Initial value of the ImageURL property.</param>
        public static Photo CreatePhoto(global::System.Int32 id, global::System.String imageURL)
        {
            Photo photo = new Photo();
            photo.Id = id;
            photo.ImageURL = imageURL;
            return photo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImageURL
        {
            get
            {
                return _ImageURL;
            }
            set
            {
                OnImageURLChanging(value);
                ReportPropertyChanging("ImageURL");
                _ImageURL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImageURL");
                OnImageURLChanged();
            }
        }
        private global::System.String _ImageURL;
        partial void OnImageURLChanging(global::System.String value);
        partial void OnImageURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Caption
        {
            get
            {
                return _Caption;
            }
            set
            {
                OnCaptionChanging(value);
                ReportPropertyChanging("Caption");
                _Caption = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Caption");
                OnCaptionChanged();
            }
        }
        private global::System.String _Caption;
        partial void OnCaptionChanging(global::System.String value);
        partial void OnCaptionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlexAndNikkiDBModel", Name="Profile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Profile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Profile object.
        /// </summary>
        /// <param name="username">Initial value of the Username property.</param>
        public static Profile CreateProfile(global::System.String username)
        {
            Profile profile = new Profile();
            profile.Username = username;
            return profile;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                if (_Username != value)
                {
                    OnUsernameChanging(value);
                    ReportPropertyChanging("Username");
                    _Username = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Username");
                    OnUsernameChanged();
                }
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MSN
        {
            get
            {
                return _MSN;
            }
            set
            {
                OnMSNChanging(value);
                ReportPropertyChanging("MSN");
                _MSN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MSN");
                OnMSNChanged();
            }
        }
        private global::System.String _MSN;
        partial void OnMSNChanging(global::System.String value);
        partial void OnMSNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Yahoo
        {
            get
            {
                return _Yahoo;
            }
            set
            {
                OnYahooChanging(value);
                ReportPropertyChanging("Yahoo");
                _Yahoo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Yahoo");
                OnYahooChanged();
            }
        }
        private global::System.String _Yahoo;
        partial void OnYahooChanging(global::System.String value);
        partial void OnYahooChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GoogleTalk
        {
            get
            {
                return _GoogleTalk;
            }
            set
            {
                OnGoogleTalkChanging(value);
                ReportPropertyChanging("GoogleTalk");
                _GoogleTalk = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GoogleTalk");
                OnGoogleTalkChanged();
            }
        }
        private global::System.String _GoogleTalk;
        partial void OnGoogleTalkChanging(global::System.String value);
        partial void OnGoogleTalkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Facebook
        {
            get
            {
                return _Facebook;
            }
            set
            {
                OnFacebookChanging(value);
                ReportPropertyChanging("Facebook");
                _Facebook = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Facebook");
                OnFacebookChanged();
            }
        }
        private global::System.String _Facebook;
        partial void OnFacebookChanging(global::System.String value);
        partial void OnFacebookChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlexAndNikkiDBModel", "FK_Profiles_Users", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AlexAndNikkiDBModel.FK_Profiles_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AlexAndNikkiDBModel.FK_Profiles_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AlexAndNikkiDBModel.FK_Profiles_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("AlexAndNikkiDBModel.FK_Profiles_Users", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlexAndNikkiDBModel", Name="StaticPage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StaticPage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StaticPage object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        public static StaticPage CreateStaticPage(global::System.String name)
        {
            StaticPage staticPage = new StaticPage();
            staticPage.Name = name;
            return staticPage;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlexAndNikkiDBModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static User CreateUser(global::System.String username, global::System.String password)
        {
            User user = new User();
            user.Username = username;
            user.Password = password;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                if (_Username != value)
                {
                    OnUsernameChanging(value);
                    ReportPropertyChanging("Username");
                    _Username = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Username");
                    OnUsernameChanged();
                }
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlexAndNikkiDBModel", "FK_BlogPosts_Users", "BlogPosts")]
        public EntityCollection<BlogPost> BlogPosts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BlogPost>("AlexAndNikkiDBModel.FK_BlogPosts_Users", "BlogPosts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BlogPost>("AlexAndNikkiDBModel.FK_BlogPosts_Users", "BlogPosts", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlexAndNikkiDBModel", "FK_Profiles_Users", "Profiles")]
        public Profile Profile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profile>("AlexAndNikkiDBModel.FK_Profiles_Users", "Profiles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profile>("AlexAndNikkiDBModel.FK_Profiles_Users", "Profiles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Profile> ProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profile>("AlexAndNikkiDBModel.FK_Profiles_Users", "Profiles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Profile>("AlexAndNikkiDBModel.FK_Profiles_Users", "Profiles", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
